### ISSUE TITLE
How to insert text only when Enter key pressed?

### ISSUE THREAD

**Issue by adoyle-h** [uga-rosa/cmp-dynamic#1]
I don't want insert text when hover on completion entry. Because when `cb` returned a large string, it looks messy.

I want to preview the result in preview window, and insert result into buffer only when `Enter` pressed. 

If set `insertText = 0`, it will insert `0` when press `Enter`.

**Comment by uga-rosa** [comment]
The `insertText` is a field for inserting a string that is different from the `label`. See [this](
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem).

This is a issue with the cmp body's settings. You can use the following.
```lua
local cmp = require("cmp")

cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })
cmp.select_prev_item({ behavior = cmp.SelectBehavior.Select })
```

**Comment by uga-rosa** [comment]
You can use the `detail` or `documentation` field for the preview.

```lua
local Date = require("cmp_dynamic.utils.date")

require("cmp_dynamic").setup({
    {
        label = "today",
        insertText = 1,
        detail = 1,
        cb = {
            function()
                return os.date("%Y/%m/%d")
            end,
        },
    },
})
```
![image](https://user-images.githubusercontent.com/82267684/197378964-6dd22052-e8d8-4649-96e1-eca2972a8c92.png)

**Comment by adoyle-h** [comment]
> The insertText is a field for inserting a string that is different from the label. See this.

Thanks for your information. I have learned the interface `CompletionItem` now.

> This is a issue with the cmp body's settings. You can use the following.

But it's not a nvim-cmp settings issue. I'm using `cmp.select_next_item({ behavior = cmp.SelectBehavior.Insert })` with `cmp-snippy` that work as expected. It inserts dynamic snippets only when Enter pressed.

<img width="447" alt="CleanShot 2022-10-24 at 18 18 08@2x" src="https://user-images.githubusercontent.com/1998490/197504331-dfe1b8e1-2ee0-4f3e-a293-b4d952a81a40.png">

Because the `cmp-snippy` using the [`source:resolve`](https://github.com/dcampos/cmp-snippy/blob/9af1635fe40385ffa3dabf322039cb5ae1fd7d35/lua/cmp_snippy/init.lua#L38) to display preview text, and [`source:execute`](https://github.com/dcampos/cmp-snippy/blob/9af1635fe40385ffa3dabf322039cb5ae1fd7d35/lua/cmp_snippy/init.lua#L56) to expand snippet.
It's the right way to create a nvim-cmp source that follows the [definition](https://github.com/hrsh7th/nvim-cmp/blob/cdb77665bbf23bd2717d424ddf4bf98057c30bb3/doc/cmp.txt#L770-L783).

It's unnecessary that put all things in `source:complete`. Because all callback functions will be invoked while getting completion list.

I have completely rewritten [cmp-dynamic](https://github.com/adoyle-h/neovim-config/blob/feat/lsp/lua/adoyle-neovim-config/plugins/completion/dynamic/source.lua) in my project for your reference.

**Comment by uga-rosa** [comment]
I don't usually press `<CR>`. So `source:resolve`, which doesn't expand unless `<CR>` is pressed, is inconvenient, so I dared to do this.
But if there are others like you, I will add it as an option.
